# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-09-22 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0005_auto_20180922_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='Unknown breed', max_length=255),
        ),
    ]
